name: mvvm
description: MVVM flutter scaffolding CLI
version: 1.0.0
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  args: any
  path: any
  get_it: ^8.1.1

dev_dependencies:
  json_serializable: ^6.6.0
  build_runner: ^2.4.6

executables:
  mvvm:
